import test from 'node:test';
import assert from 'node:assert/strict';
import { BrowserStore, parseState, STORAGE_KEY, type StorageAdapter } from '../lib/storage';
import { confirmReservation } from '../lib/domain';
import { priceStay } from '../lib/pricing';
class MemoryStorage implements StorageAdapter { data=new Map<string,string>(); reads=0; writes=0; fail=false; getItem(key:string){this.reads++;return this.data.get(key)??null;} setItem(key:string,value:string){if(this.fail)throw new Error('QuotaExceededError');this.writes++;this.data.set(key,value);} removeItem(key:string){this.data.delete(key);} }
const clock=()=>new Date('2026-09-09T09:00:00Z');
test('SSR starts empty and hydration seeds once then preserves saved state on refresh',()=>{const storage=new MemoryStorage();const first=new BrowserStore(()=>storage,clock);assert.equal(first.getServerSnapshot().ready,false);assert.equal(storage.reads,0);first.initialize();assert.equal(storage.writes,1);first.initialize();assert.equal(storage.writes,1);first.updateDraft({arrival:'2026-10-01'});const second=new BrowserStore(()=>storage,()=>new Date('2026-10-01T12:00:00Z'));second.initialize();assert.equal(second.getSnapshot().state!.seedAnchor,'2026-09-09');assert.equal(second.getSnapshot().state!.draft.arrival,'2026-10-01');assert.deepEqual(second.getSnapshot().state,first.getSnapshot().state);});
test('re-read before mutation avoids stale whole-state replacement across tabs',()=>{const storage=new MemoryStorage();const a=new BrowserStore(()=>storage,clock),b=new BrowserStore(()=>storage,clock);a.initialize();b.initialize();a.updateDraft({arrival:'2026-10-01'});b.updateDraft({departure:'2026-10-04'});a.synchronize();assert.equal(a.getSnapshot().state!.draft.arrival,'2026-10-01');assert.equal(a.getSnapshot().state!.draft.departure,'2026-10-04');assert.equal(a.getSnapshot().state!.revision,2);});
test('corrupt/unsupported data is preserved, explicit temporary fallback permits changes',()=>{for(const bad of ['{broken','{"schemaVersion":2}']){const storage=new MemoryStorage();storage.data.set(STORAGE_KEY,bad);const store=new BrowserStore(()=>storage,clock);store.initialize();assert.ok(store.getSnapshot().warning);assert.equal(storage.getItem(STORAGE_KEY),bad);assert.equal(store.getSnapshot().recovery,bad);assert.throws(()=>store.updateDraft({adults:1}),/Storage needs attention/);store.useTemporary();store.updateDraft({adults:1});assert.equal(store.getSnapshot().state!.draft.adults,1);assert.equal(storage.getItem(STORAGE_KEY),bad);}});
test('initial storage access denied keeps browsing functional',()=>{const store=new BrowserStore(()=>{throw new Error('Access denied');},clock);store.initialize();assert.equal(store.getSnapshot().ready,true);assert.ok(store.getSnapshot().state);assert.ok(store.getSnapshot().warning.includes('Access denied'));store.useTemporary();store.updateDraft({adults:1});assert.equal(store.getSnapshot().state!.draft.adults,1);});
test('failed reservation persistence publishes no success and retry can use explicit temporary mode',()=>{const storage=new MemoryStorage();const store=new BrowserStore(()=>storage,clock);store.initialize();store.updateDraft({arrival:'2026-10-01',departure:'2026-10-03',roomSlug:'courtyard-room',guest:{name:'Alex Rowan',email:'alex@example.com',requests:''}});const draft=structuredClone(store.getSnapshot().state!.draft);const before=storage.getItem(STORAGE_KEY);const total=priceStay(19000,draft,draft.extras).total;storage.fail=true;assert.throws(()=>store.mutate(s=>confirmReservation(s,draft,'2026-09-09',clock().toISOString(),'success',total)),/not durably saved/);assert.equal(storage.getItem(STORAGE_KEY),before);assert.equal(store.getSnapshot().state!.messages.length,0);store.useTemporary();store.mutate(s=>confirmReservation(s,draft,'2026-09-09',clock().toISOString(),'success',total));assert.equal(store.getSnapshot().state!.messages.length,1);assert.equal(storage.getItem(STORAGE_KEY),before);});
test('reset touches only app keys and failed reset preserves prior stored state',()=>{const storage=new MemoryStorage();const store=new BrowserStore(()=>storage,clock);store.initialize();storage.data.set('other-app:important','keep me');store.updateDraft({arrival:'2026-10-01'});const before=storage.getItem(STORAGE_KEY);storage.fail=true;assert.throws(()=>store.reset(),/not durably saved/);assert.equal(storage.getItem(STORAGE_KEY),before);storage.fail=false;store.reset();assert.equal(storage.getItem('other-app:important'),'keep me');assert.equal(store.getSnapshot().state!.draft.arrival,'');assert.equal(store.getSnapshot().warning,'');});
test('invalid draft counts survive hydration for useful inline validation, but invalid envelopes do not',()=>{const storage=new MemoryStorage();const store=new BrowserStore(()=>storage,clock);store.initialize();store.updateDraft({adults:1.5,children:-1});assert.equal(parseState(storage.getItem(STORAGE_KEY)!).draft.adults,1.5);const broken=JSON.parse(storage.getItem(STORAGE_KEY)!);broken.reservations[0].quote=null;assert.throws(()=>parseState(JSON.stringify(broken)),/reservations contain invalid/);});
test('older schema is deliberately preserved until scoped reset',()=>{const storage=new MemoryStorage();storage.data.set('aurel-house:demo:v0','old data');const store=new BrowserStore(()=>storage,clock);store.initialize();assert.ok(store.getSnapshot().warning.includes('older'));assert.equal(storage.getItem('aurel-house:demo:v0'),'old data');store.reset();assert.equal(storage.getItem('aurel-house:demo:v0'),null);assert.ok(parseState(storage.getItem(STORAGE_KEY)!));});
test('mutation exceptions roll back all partial candidate changes',()=>{const storage=new MemoryStorage();const store=new BrowserStore(()=>storage,clock);store.initialize();const before=structuredClone(store.getSnapshot().state);assert.throws(()=>store.mutate(s=>{s.draft.adults=1;throw new Error('failed validation');}),/failed validation/);assert.deepEqual(store.getSnapshot().state,before);});
test('storage reset event discards obsolete draft and exposes recovery instead of stale saving',()=>{const storage=new MemoryStorage();const store=new BrowserStore(()=>storage,clock);store.initialize();store.updateDraft({arrival:'2026-10-01'});storage.removeItem(STORAGE_KEY);store.synchronize();assert.equal(store.getSnapshot().state!.draft.arrival,'');assert.ok(store.getSnapshot().warning);assert.throws(()=>store.updateDraft({adults:1}),/Storage needs attention/);});
