'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, ArrowUpRight, CalendarDays, Check, X, Trash2 } from 'lucide-react';
import { ROOMS, type RoomSlug } from '@/lib/catalog';
import { addDays, dateLabel, hotelToday, isDate } from '@/lib/dates';
import { money } from '@/lib/pricing';
import { dailyMetrics, unitState, addMaintenance, removeMaintenance, editRoom } from '@/lib/front-desk';
import { resolvedRoom, transitionReservation } from '@/lib/domain';
import { browserStore, newId } from '@/lib/storage';
import type { DemoState, Reservation, ReservationStatus } from '@/lib/types';
import { useHouse } from './store-provider';
import { Emblem } from './identity';
import { Photo } from './photo';
import { Status } from './stays';
import { PriceBreakdown } from './quote';
const TABS = ['Today', 'Reservations', 'Availability', 'Rooms & rates', 'Maintenance', 'Inquiries & messages', 'Activity'];
function ReservationsTable({ reservations, onSelect }: { reservations: Reservation[]; onSelect: (ref: string) => void }) {
  return reservations.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Reservations table"><table className="reservation-table"><thead><tr><th>Guest / reference</th><th>Room</th><th>Arrival</th><th>Departure</th><th>Status</th><th>Simulated total</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{reservations.map(r => <tr key={r.ref}><td><strong>{r.guest.name}</strong><small>{r.ref} · {r.source}</small></td><td>{r.roomName}<small>{r.unitId} · {r.adults + r.children} guests</small></td><td>{dateLabel(r.arrival, { month: 'short', day: 'numeric' })}</td><td>{dateLabel(r.departure, { month: 'short', day: 'numeric' })}</td><td><Status reservation={r} /></td><td>{money(r.quote.total)}</td><td><button className="icon-button" aria-label={`Open ${r.ref}`} onClick={() => onSelect(r.ref)}><ArrowUpRight size={18} /></button></td></tr>)}</tbody></table></div> : <p className="admin-empty">No reservations match this view.</p>;
}
function Availability({ state, date, onSelect }: { state: DemoState; date: string; onSelect: (ref: string) => void }) {
  const days = Array.from({ length: 7 }, (_, i) => addDays(date, i));
  return <><p className="small muted">Each cell represents one occupied night, with departure excluded. Select an occupied unit for its reservation. The mobile view shows the selected day.</p><div className="calendar-legend"><span>Available</span><span>Occupied</span><span>Maintenance</span></div><div className="availability-desktop table-scroll"><table className="availability-table"><caption>Seven nights from {dateLabel(date)} · Local demo inventory</caption><thead><tr><th>Physical unit</th>{days.map(day => <th key={day}>{dateLabel(day, { weekday: 'short', day: 'numeric', month: 'short' })}</th>)}</tr></thead><tbody>{ROOMS.flatMap(room => room.units.map(unit => <tr key={unit}><th>{unit}<small>{resolvedRoom(state, room.slug).name}</small></th>{days.map(day => { const cell = unitState(state, unit, day); return <td key={day} className={`unit-${cell.kind}`}>{cell.ref ? <button aria-label={`${unit}, ${day}: ${cell.detail}`} onClick={() => onSelect(cell.ref!)}>Occupied</button> : <span title={cell.detail}>{cell.label}</span>}</td>; })}</tr>))}</tbody></table></div><div className="availability-mobile">{ROOMS.map(room => <section key={room.slug}><h3>{resolvedRoom(state, room.slug).name}</h3>{room.units.map(unit => { const cell = unitState(state, unit, date); return <div className={`unit-list-row unit-${cell.kind}`} key={unit}><strong>{unit}</strong><span>{cell.label}</span>{cell.ref ? <button className="icon-button" onClick={() => onSelect(cell.ref!)} aria-label={`Open ${unit} reservation`}><ArrowUpRight size={18} /></button> : <small>{cell.detail}</small>}</div>; })}</section>)}</div></>;
}
function RoomEditor({ state, slug, report }: { state: DemoState; slug: RoomSlug; report: (message: string, failed?: boolean) => void }) {
  const room = resolvedRoom(state, slug);
  return <form className="room-editor" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const rate = String(data.get('rate')); try { if (!/^\d+(\.\d{1,2})?$/.test(rate)) throw new Error('Use a rate with at most two decimal places.'); browserStore.mutate(current => editRoom(current, slug, { baseRate: Math.round(Number(rate) * 100), name: String(data.get('name')).trim(), short: String(data.get('short')).trim(), description: String(data.get('description')).trim() }, new Date().toISOString(), newId())); report(`Saved local changes to ${slug}. Existing accepted prices are unchanged.`); } catch (error) { report((error as Error).message, true); } }}><Photo id={`${slug}-1`} sizes="300px" /><div><h3>{room.name}</h3><p className="small muted">{room.units.join(', ')} · {room.area} m² · Up to {room.capacity} guests</p><div className="form-grid"><div className="field"><label htmlFor={`${slug}-rate`}>Base rate · USD/night</label><input name="rate" id={`${slug}-rate`} type="number" min="1" max="10000" step="0.01" defaultValue={room.baseRate / 100} required /></div><div className="field"><label htmlFor={`${slug}-name`}>Room name</label><input name="name" id={`${slug}-name`} defaultValue={room.name} required minLength={3} maxLength={160} /></div><div className="field full"><label htmlFor={`${slug}-short`}>Short description</label><input name="short" id={`${slug}-short`} defaultValue={room.short} required minLength={3} maxLength={160} /></div><div className="field full"><label htmlFor={`${slug}-description`}>Room story</label><textarea name="description" id={`${slug}-description`} defaultValue={room.description} required minLength={3} maxLength={1500} /></div></div><button className="button" type="submit">Save local room changes <Check size={16} /></button></div></form>;
}
export function Dashboard() {
  const { state } = useHouse(); const [tab, setTab] = useState('Today'); const [selectedDate, setSelectedDate] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [source, setSource] = useState('All'); const [selectedRef, setSelectedRef] = useState(''); const [notice, setNotice] = useState({ text: '', failed: false }); const [cancelAsked, setCancelAsked] = useState(false); const drawer = useRef<HTMLDialogElement>(null);
  if (!state) return <div className="loading-state"><Emblem /><p>Opening your local front desk…</p></div>;
  const today = hotelToday(); const date = isDate(selectedDate) ? selectedDate : today; const metrics = dailyMetrics(state, date); const selected = state.reservations.find(r => r.ref === selectedRef);
  const report = (text: string, failed = false) => setNotice({ text, failed });
  const open = (ref: string) => { setSelectedRef(ref); setCancelAsked(false); drawer.current?.showModal(); };
  const filtered = state.reservations.filter(r => (status === 'All' || r.status === status) && (source === 'All' || r.source === source) && `${r.guest.name} ${r.guest.email} ${r.ref} ${r.roomName} ${r.unitId}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const transition = (next: ReservationStatus) => { try { browserStore.mutate(current => transitionReservation(current, selectedRef, next, today, new Date().toISOString())); report(`Reservation ${selectedRef} is now ${next.replaceAll('-', ' ')}. All amounts are simulated.`); setCancelAsked(false); } catch (error) { report((error as Error).message, true); } };
  return <div className="dashboard wrap"><div className="dashboard-heading"><div><span className="small">AUREL HOUSE / LOCAL FRONT DESK</span><h1>A good day at the house.</h1><p>Open demo access · This browser’s records · No sign-in or real payments</p></div><Link className="text-link" href="/demo/">Demo guide <ArrowUpRight size={17} /></Link></div><div className="dashboard-toolbar"><nav aria-label="Dashboard sections">{TABS.map(item => <button aria-current={tab === item ? 'page' : undefined} key={item} onClick={() => { setTab(item); setNotice({ text: '', failed: false }); }}>{item}</button>)}</nav><div className="dashboard-date"><button className="icon-button" aria-label="Previous date" onClick={() => setSelectedDate(addDays(date, -1))}><ArrowLeft size={17} /></button><label><CalendarDays size={17} /><span className="sr-only">Dashboard date</span><input type="date" value={date} onChange={e => setSelectedDate(e.target.value)} /></label><button className="icon-button" aria-label="Next date" onClick={() => setSelectedDate(addDays(date, 1))}><ArrowRight size={17} /></button><button className="text-button" onClick={() => setSelectedDate(today)}>Today</button></div></div>
  {notice.text && <div className={notice.failed ? 'form-alert' : 'form-success'} role={notice.failed ? 'alert' : 'status'}>{notice.text}</div>}
  {tab === 'Today' && <><section className="dashboard-metrics" aria-label={`House metrics for ${date}`}><div><span>Arrivals</span><strong>{metrics.arrivals.length}</strong><small>For {dateLabel(date, { month: 'short', day: 'numeric' })}</small></div><div><span>Departures</span><strong>{metrics.departures.length}</strong><small>Checkout by 11:00</small></div><div><span>Night occupancy</span><strong>{metrics.occupancy}%</strong><small>{metrics.occupied} of 12 physical rooms</small></div><div><span>Available rooms</span><strong>{metrics.available}</strong><small>{metrics.blocked} under maintenance</small></div></section><section className="admin-section"><h2>Arriving at the house.</h2><ReservationsTable reservations={metrics.arrivals} onSelect={open} /></section><section className="admin-section"><h2>Until next time.</h2><ReservationsTable reservations={metrics.departures} onSelect={open} /></section><section className="admin-section"><div className="admin-section-title"><h2>Recent reservations.</h2><button className="text-button" onClick={() => setTab('Reservations')}>View all reservations</button></div><ReservationsTable reservations={[...state.reservations].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,5)} onSelect={open} /></section></>}
  {tab === 'Reservations' && <section className="admin-section"><h2>Every stay, in one place.</h2><div className="admin-filters"><div className="field"><label htmlFor="reservation-search">Search guests, rooms or references</label><input id="reservation-search" type="search" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="field"><label htmlFor="reservation-status">Status</label><select id="reservation-status" value={status} onChange={e => setStatus(e.target.value)}><option>All</option>{['confirmed', 'checked-in', 'checked-out', 'cancelled'].map(value => <option key={value} value={value}>{value.replaceAll('-', ' ')}</option>)}</select></div><div className="field"><label htmlFor="reservation-source">Source</label><select id="reservation-source" value={source} onChange={e => setSource(e.target.value)}><option>All</option><option value="visitor">Visitor-created</option><option value="sample">Sample</option></select></div></div><ReservationsTable reservations={filtered} onSelect={open} /><p className="small muted">{filtered.length} matching records. Status changes use the actual hotel date, {dateLabel(today)}, independently of the date selected for viewing.</p></section>}
  {tab === 'Availability' && <section className="admin-section"><h2>Twelve rooms. Seven nights.</h2><Availability state={state} date={date} onSelect={open} /></section>}
  {tab === 'Rooms & rates' && <section className="admin-section"><h2>The rooms, thoughtfully maintained.</h2><p>Changes update this browser’s storefront and new quotes. Accepted reservations keep their price, room-name and policy snapshots. Capacity, units and actual outlooks remain tied to the fictional catalog.</p>{ROOMS.map(room => <RoomEditor state={state} slug={room.slug} report={report} key={`${room.slug}-${JSON.stringify(state.roomOverrides[room.slug])}`} />)}</section>}
  {tab === 'Maintenance' && <section className="admin-section"><h2>A little care for the house.</h2><p>Block a specific physical unit for whole nights. Existing reservations and maintenance must be resolved before adding a conflicting block.</p><form className="maintenance-form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); try { browserStore.mutate(current => addMaintenance(current, { id: newId(), unitId: String(data.get('unit')), arrival: String(data.get('arrival')), departure: String(data.get('departure')), reason: String(data.get('reason')) }, today, new Date().toISOString())); report('Maintenance saved. Availability has been recalculated from the local records.'); } catch (error) { report((error as Error).message, true); } }}><div className="form-grid"><div className="field"><label htmlFor="block-unit">Physical room unit</label><select id="block-unit" name="unit">{ROOMS.map(room => <optgroup key={room.slug} label={room.name}>{room.units.map(unit => <option key={unit}>{unit}</option>)}</optgroup>)}</select></div><div className="field"><label htmlFor="block-reason">Reason</label><input id="block-reason" name="reason" required minLength={3} maxLength={300} placeholder="For example, limewash touch-up" /></div><div className="field"><label htmlFor="block-arrival">First blocked night</label><input type="date" id="block-arrival" name="arrival" defaultValue={date >= today ? date : today} min={today} max={addDays(today,365)} required /></div><div className="field"><label htmlFor="block-departure">Available again on</label><input type="date" id="block-departure" name="departure" defaultValue={addDays(date >= today ? date : today, 1)} min={addDays(today,1)} max={addDays(today,366)} required /></div></div><button className="button" type="submit">Save maintenance block <Check size={16} /></button></form><div className="maintenance-list">{state.maintenance.map(block => <div key={block.id}><div><strong>{block.unitId} · {block.reason}</strong><p>{dateLabel(block.arrival)} — {dateLabel(block.departure)} (end excluded)</p></div><button className="icon-button" aria-label={`Remove maintenance ${block.unitId} ${block.reason}`} onClick={() => { try { browserStore.mutate(current => removeMaintenance(current, block.id, new Date().toISOString())); report(`Maintenance removed from ${block.unitId}.`); } catch (error) { report((error as Error).message, true); } }}><Trash2 size={18} /></button></div>)}</div></section>}
  {tab === 'Inquiries & messages' && <section className="admin-section"><h2>Notes to the house.</h2><p>Locally saved inquiries and generated message previews. Nothing here was emailed or delivered to a hotel.</p><h3>Inquiries · {state.inquiries.length}</h3>{state.inquiries.length ? [...state.inquiries].reverse().map(inquiry => <details className="message-preview" key={inquiry.id}><summary><strong>{inquiry.subject}</strong><span>{inquiry.name} · {dateLabel(inquiry.createdAt.slice(0,10))}</span></summary><p className="small muted">{inquiry.email} · Saved in this demo</p><p className="preserve-lines">{inquiry.message}</p></details>) : <p className="admin-empty">No inquiries yet. Save a note from Contact, Dining or an Experience.</p>}<h3>Confirmation-message previews · {state.messages.length}</h3>{state.messages.length ? [...state.messages].reverse().map(message => <details className="message-preview" key={message.id}><summary><strong>{message.subject}</strong><span>{message.recipient} · Local preview only</span></summary><p className="preserve-lines">{message.body}</p><button className="text-button" onClick={() => open(message.ref)}>View the reservation</button></details>) : <p className="admin-empty">Confirm a visitor booking to generate its local message preview.</p>}</section>}
  {tab === 'Activity' && <section className="admin-section"><h2>The house ledger.</h2><p>Events saved in this browser. Charges, refunds and price differences are simulations.</p><ol className="activity-list">{[...state.activity].reverse().map(activity => <li key={activity.id}><div><strong>{activity.action}</strong><span>{new Intl.DateTimeFormat('en-US', { timeZone: 'Europe/Athens', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(activity.at))} · Europe/Athens</span>{activity.ref && <button className="text-button" onClick={() => open(activity.ref!)}>{activity.ref}</button>}</div>{activity.amount !== undefined && <span>{activity.amount < 0 ? '−' : '+'}{money(Math.abs(activity.amount))}<small>simulated</small></span>}</li>)}</ol></section>}
  <div className="dashboard-footer"><span>Seed anchor: {state.seedAnchor} · Revision {state.revision}</span><Link href="/demo/">Sample-data and reset controls</Link></div>
  <dialog className="reservation-drawer" ref={drawer}><div className="dialog-top"><span className="small">LOCAL RESERVATION</span><button className="icon-button" onClick={() => drawer.current?.close()} aria-label="Close reservation details"><X /></button></div>{selected && <><h2>{selected.guest.name}</h2><p className="booking-reference">{selected.ref}</p><Status reservation={selected} /><h3>{selected.roomName}</h3><p>{dateLabel(selected.arrival)} — {dateLabel(selected.departure)}<br />Unit {selected.unitId} · {selected.adults} adults · {selected.children} children<br />{selected.guest.email}</p><p className="small">{selected.guest.requests || 'No special requests.'}</p><PriceBreakdown quote={selected.quote} /><p className="small muted">Status actions use today in Europe/Athens: {dateLabel(today)}.</p><div className="drawer-actions">{selected.status === 'confirmed' && selected.arrival <= today && today < selected.departure && <button className="button" onClick={() => transition('checked-in')}>Check in guest</button>}{selected.status === 'checked-in' && today >= selected.departure && <button className="button" onClick={() => transition('checked-out')}>Check out guest</button>}{selected.status === 'checked-in' && today < selected.departure && <p className="small muted">Checkout becomes available on the scheduled departure date.</p>}{selected.status === 'confirmed' && selected.arrival > today && <><Link className="button outline-button" href={`/book/?amend=${encodeURIComponent(selected.ref)}`} onClick={() => drawer.current?.close()}>Amend this stay</Link>{!cancelAsked ? <button className="text-button" onClick={() => setCancelAsked(true)}>Cancel with full simulated refund</button> : <div className="drawer-cancel"><p>Cancel and simulate a refund of {money(selected.quote.total)}?</p><button className="button" onClick={() => transition('cancelled')}>Confirm cancellation</button><button className="text-button" onClick={() => setCancelAsked(false)}>Keep reservation</button></div>}</>}{selected.status === 'confirmed' && selected.departure <= today && <p className="small muted">This stay’s dates have passed without check-in. It remains in the historical record; backdated status changes are not allowed.</p>}<Link className="text-link" href={`/my-stay/details/?ref=${encodeURIComponent(selected.ref)}`} onClick={() => drawer.current?.close()}>Guest view <ArrowUpRight size={16} /></Link></div>{notice.text && <div className={notice.failed ? 'form-alert' : 'form-success'} role={notice.failed ? 'alert' : 'status'}>{notice.text}</div>}</>}</dialog></div>;
}
