'use client';
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { ArrowUpRight, Check } from 'lucide-react';
import { useHouse } from './store-provider';
import { browserStore, newId } from '@/lib/storage';
import { guestErrors } from '@/lib/domain';
export function InquiryForm() {
  const query = useSearchParams(); const { state, temporary } = useHouse();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [subject, setSubject] = useState((query.get('subject') || 'A stay at the house').slice(0, 180)); const [message, setMessage] = useState(''); const [errors, setErrors] = useState<Record<string, string>>({}); const [saved, setSaved] = useState('');
  return <form className="inquiry-form" noValidate onSubmit={event => { event.preventDefault(); const errors = guestErrors({ name, email, requests: '' }); if (subject.trim().length < 2) errors.subject = 'Add a subject for your inquiry.'; if (message.trim().length < 10 || message.length > 2000) errors.message = 'Tell us a little more, between 10 and 2,000 characters.'; setErrors(errors); if (Object.keys(errors).length) return; try { const id = newId(); browserStore.mutate(state => { state.inquiries.push({ id, name: name.trim(), email: email.trim(), subject: subject.trim(), message: message.trim(), createdAt: new Date().toISOString() }); state.activity.push({ id: `inquiry-${id}`, action: 'Inquiry saved in this demo', at: new Date().toISOString() }); }); setSaved(id); } catch (error) { setErrors({ save: (error as Error).message }); } }}>
    <h2>A note to the house.</h2><p>Tell us what you have in mind. Please use fictional details; your note stays in this browser.</p>
    {saved ? <div className="saved-inquiry" role="status"><Check size={32} /><h3>Saved in this demo.</h3><p>{temporary ? 'Your inquiry is kept for this temporary session only.' : 'Your inquiry is saved in this browser and appears in the hotel dashboard.'} No email was sent and no hotel has received it.</p><button className="text-button" type="button" onClick={() => { setSaved(''); setMessage(''); }}>Write another note</button></div> : <>
    <button type="button" className="text-button sample-guest" onClick={() => { setName('Alex Rowan'); setEmail('alex.rowan@example.com'); setMessage('We are imagining a quiet few days by the sea. Could you tell us more about this fictional stay?'); }}>Use sample guest</button>
    <div className="form-grid"><div className="field"><label htmlFor="inquiry-name">Your name</label><input id="inquiry-name" autoComplete="off" value={name} maxLength={100} onChange={e => setName(e.target.value)} aria-invalid={!!errors.name} aria-describedby={errors.name ? 'inquiry-name-error' : undefined} />{errors.name && <p id="inquiry-name-error" className="field-error">{errors.name}</p>}</div><div className="field"><label htmlFor="inquiry-email">Email</label><input id="inquiry-email" type="email" autoComplete="off" value={email} maxLength={180} onChange={e => setEmail(e.target.value)} aria-invalid={!!errors.email} aria-describedby={errors.email ? 'inquiry-email-error' : undefined} />{errors.email && <p id="inquiry-email-error" className="field-error">{errors.email}</p>}</div><div className="field full"><label htmlFor="inquiry-subject">What is on your mind?</label><input id="inquiry-subject" value={subject} maxLength={180} onChange={e => setSubject(e.target.value)} aria-invalid={!!errors.subject} />{errors.subject && <p className="field-error">{errors.subject}</p>}</div><div className="field full"><label htmlFor="inquiry-message">Your note</label><textarea id="inquiry-message" value={message} maxLength={2000} onChange={e => setMessage(e.target.value)} aria-invalid={!!errors.message} aria-describedby={errors.message ? 'inquiry-message-error' : undefined} />{errors.message && <p id="inquiry-message-error" className="field-error">{errors.message}</p>}</div></div>{errors.save && <p role="alert" className="field-error">{errors.save}</p>}<button className="button" disabled={!state} type="submit">Save demo inquiry <ArrowUpRight size={17} /></button><p className="small muted">No outbound messages. No reservation is created.</p></>}
  </form>;
}
