'use client';
import Link from 'next/link';
import { ArrowUpRight, BedDouble, Maximize2, Users, Check } from 'lucide-react';
import { ROOMS, getRoom, POLICY, type RoomSlug } from '@/lib/catalog';
import { resolvedRoom } from '@/lib/domain';
import { hotelToday, stayErrors } from '@/lib/dates';
import { money, priceStay } from '@/lib/pricing';
import { useHouse } from './store-provider';
import { RoomAvailability } from './search';
import { Photo } from './photo';
export function RoomPrice({ slug }: { slug: RoomSlug }) {
  const { state } = useHouse(); const room = state ? resolvedRoom(state, slug) : getRoom(slug)!;
  const valid = state && Object.keys(stayErrors(state.draft, hotelToday(), room.capacity)).length === 0;
  return <div className="room-price">{valid ? <><strong>{money(priceStay(room.baseRate, state.draft, state.draft.extras).total)}</strong><span>for your selected stay, including selected extras</span></> : <><strong>From {money(room.baseRate)}</strong><span>per night · base rate</span></>}</div>;
}
export function HomeRooms() { const { state } = useHouse(); return <div className="selected-room-grid">{ROOMS.slice(0,2).map((base,i) => { const room = state ? resolvedRoom(state,base.slug) : base; return <article key={room.slug}><Link className="image-link" href={`/rooms/${room.slug}/`}><Photo id={`${room.slug}-1`} sizes="(max-width:700px) 100vw, 50vw" /><span className="image-arrow"><ArrowUpRight size={24} /></span></Link><div className="room-caption"><div><span className="small">{room.view} · {room.area} m²</span><h3><Link href={`/rooms/${room.slug}/`}>{room.name}</Link></h3></div><RoomPrice slug={room.slug} /></div>{i === 0 && <p className="room-whisper">{room.feeling}</p>}</article>; })}</div>; }
export function RoomIndex() {
  const { state } = useHouse();
  return <div className="rooms-index">{ROOMS.map((base, index) => { const room = state ? resolvedRoom(state, base.slug) : base; return <article className="room-index-row" key={room.slug}><Link className="image-link" href={`/rooms/${room.slug}/`}><Photo id={`${room.slug}-1`} priority={index === 0} /><span className="image-arrow"><ArrowUpRight size={22} /></span></Link><div><p className="small">{room.view}</p><h2><Link href={`/rooms/${room.slug}/`}>{room.name}</Link></h2><p>{room.short}</p><dl className="room-facts"><div><Maximize2 size={17} /><dt>Area</dt><dd>{room.area} m²</dd></div><div><Users size={17} /><dt>Occupancy</dt><dd>Up to {room.capacity}</dd></div><div><BedDouble size={18} /><dt>Beds</dt><dd>{room.bed}</dd></div></dl><RoomPrice slug={room.slug} /><Link className="text-link" href={`/rooms/${room.slug}/`}>Step inside <ArrowUpRight size={18} /></Link></div></article>; })}<div className="group-note"><p>More than one room in mind?</p><Link className="text-link" href="/contact/?subject=Group%20stay">Tell us about your group <ArrowUpRight size={17} /></Link></div></div>;
}
export function RoomHeading({ slug }: { slug: RoomSlug }) { const { state } = useHouse(); const room = state ? resolvedRoom(state, slug) : getRoom(slug)!; return <div className="room-heading wrap"><div><Link className="back-link" href="/rooms/">Our rooms <ArrowUpRight size={14} /></Link><h1>{room.name}</h1><p>{room.feeling}</p></div><RoomPrice slug={slug} /></div>; }
export function RoomInformation({ slug }: { slug: RoomSlug }) { const { state } = useHouse(); const room = state ? resolvedRoom(state, slug) : getRoom(slug)!; return <section className="room-information wrap"><div><h2>A little more<br /><em>about your room.</em></h2><p className="room-description">{room.description}</p><dl className="room-facts"><div><Maximize2 size={19} /><dt>Room size</dt><dd>{room.area} m²</dd></div><div><Users size={19} /><dt>Guests</dt><dd>Up to {room.capacity}</dd></div><div><BedDouble size={20} /><dt>Sleeping</dt><dd>{room.bed}</dd></div></dl><h3>Considered comforts.</h3><ul className="amenities">{room.amenities.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul><h3>Stone, water, a quiet moment.</h3><p>{room.bathroom}</p><p className="small">View: {room.view}. Room images illustrate this fictional room type. Physical units share this specification. No step-free access is established; <Link href="/contact/?subject=Access%20needs">ask about access needs</Link>.</p></div><aside className="room-booking-panel"><Photo id={`${slug}-4`} /><div><h3>Make a little time.</h3><RoomPrice slug={slug} /><RoomAvailability slug={slug} /><p className="small">One room · 1–14 nights<br />No payment details needed.</p><hr /><h4>The shape of your stay</h4><p className="small">{POLICY}</p><Link href="/policies/" className="small">All stay policies</Link></div></aside></section>; }
