'use client';
import { useId, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, CalendarDays, X } from 'lucide-react';
import { useHouse } from './store-provider';
import { addDays, dateLabel, hotelToday, stayErrors, type Stay } from '@/lib/dates';
import { browserStore, newId } from '@/lib/storage';
import { sampleStay } from '@/lib/domain';
import type { RoomSlug } from '@/lib/catalog';
export function StayFields({ value, onChange, errors = {} }: { value: Stay; onChange: (patch: Partial<Stay>) => void; errors?: Record<string, string> }) {
  const id = useId(); const today = hotelToday();
  return <div className="stay-fields"><div className="field"><label htmlFor={`${id}-arrival`}>Arrival</label><input id={`${id}-arrival`} aria-invalid={!!errors.arrival} aria-describedby={errors.arrival ? `${id}-arrival-error` : undefined} type="date" value={value.arrival} min={today} max={addDays(today, 365)} onChange={e => onChange({ arrival: e.target.value })} />{errors.arrival && <p id={`${id}-arrival-error`} className="field-error">{errors.arrival}</p>}</div><div className="field"><label htmlFor={`${id}-departure`}>Departure</label><input id={`${id}-departure`} aria-invalid={!!errors.departure} aria-describedby={errors.departure ? `${id}-departure-error` : undefined} type="date" value={value.departure} min={value.arrival ? addDays(value.arrival, 1) : addDays(today, 1)} max={addDays(today, 366)} onChange={e => onChange({ departure: e.target.value })} />{errors.departure && <p id={`${id}-departure-error`} className="field-error">{errors.departure}</p>}</div><div className="field"><label htmlFor={`${id}-adults`}>Adults</label><input id={`${id}-adults`} type="number" min="1" max="4" step="1" value={value.adults} onChange={e => onChange({ adults: Number(e.target.value) })} aria-invalid={!!errors.adults} />{errors.adults && <p className="field-error">{errors.adults}</p>}</div><div className="field"><label htmlFor={`${id}-children`}>Children <span>(2–11)</span></label><input id={`${id}-children`} type="number" min="0" max="3" step="1" value={value.children} onChange={e => onChange({ children: Number(e.target.value) })} aria-invalid={!!errors.children} />{errors.children && <p className="field-error">{errors.children}</p>}</div>{errors.guests && <p className="field-error full" role="alert">{errors.guests}</p>}</div>;
}
export function SearchStrip() {
  const { state } = useHouse(); const router = useRouter(); const dialog = useRef<HTMLDialogElement>(null);
  const [errors, setErrors] = useState<Record<string, string>>({}); const [message, setMessage] = useState('');
  if (!state) return <div className="search-strip search-loading">Preparing the local house…</div>;
  const change = (patch: Partial<Stay>) => { try { browserStore.updateDraft(patch); setErrors({}); } catch (error) { setMessage((error as Error).message); } };
  const search = () => { const found = stayErrors(state.draft, hotelToday()); setErrors(found); if (Object.keys(found).length) { if (window.matchMedia('(max-width: 700px)').matches && !dialog.current?.open) dialog.current?.showModal(); return; } try { browserStore.updateDraft({ step: 1, submissionId: newId(), amendmentRef: undefined }); dialog.current?.close(); router.push('/book/'); } catch (error) { setMessage((error as Error).message); } };
  const sample = () => { try { change(sampleStay(state, hotelToday())); } catch (error) { setMessage((error as Error).message); } };
  return <div className="search-strip"><div className="search-label"><CalendarDays size={23} /><span>A little time<br /><strong>away.</strong></span></div><div className="desktop-search"><StayFields value={state.draft} onChange={change} errors={errors} /></div><button className="search-mobile-summary" onClick={() => dialog.current?.showModal()}>{state.draft.arrival ? `${dateLabel(state.draft.arrival, { month: 'short', day: 'numeric' })} — ${dateLabel(state.draft.departure, { month: 'short', day: 'numeric' })}` : 'Choose your dates'}<span>{state.draft.adults + state.draft.children} guests</span></button><div className="search-action"><button className="button sand-button" onClick={search}>Check availability <ArrowUpRight size={18} /></button><button className="sample-link" onClick={sample}>Try sample dates</button></div>{message && <p role="alert" className="full">{message}</p>}<dialog ref={dialog} className="availability-dialog"><div className="dialog-top"><h2>A little time away.</h2><button aria-label="Close availability" className="icon-button" onClick={() => dialog.current?.close()}><X /></button></div><p>One room, up to fourteen nights. Children are ages 2–11.</p><StayFields value={state.draft} onChange={change} errors={errors} /><button className="button" onClick={search}>Check availability <ArrowUpRight size={18} /></button><button className="text-button" onClick={sample}>Try sample dates</button></dialog></div>;
}
export function RoomAvailability({ slug }: { slug: RoomSlug }) {
  const { state } = useHouse(); const router = useRouter(); const [error, setError] = useState('');
  return <><button className="button" disabled={!state} onClick={() => { try { browserStore.updateDraft({ roomSlug: slug, step: 0, amendmentRef: undefined, submissionId: newId() }); router.push('/book/'); } catch (e) { setError((e as Error).message); } }}>Find your stay <ArrowUpRight size={17} /></button>{error && <p role="alert" className="field-error">{error}</p>}</>;
}
