export type Story = { slug: string; title: string; subtitle: string; image: string; detail: string; paragraphs: string[]; sections: { title: string; text: string }[] };
export const EXPERIENCES: Story[] = [
  { slug: 'along-the-coast', title: 'The long way to the water.', subtitle: 'A coastal walk', image: 'coast', detail: 'About 2 hours · Gentle pace · Fictional guided offering',
    paragraphs: ['The path begins where the garden ends. It follows the low headland through rosemary and sea fennel, keeping the water on one side and the pale shoulder of the hills on the other. There is no particular destination. That is part of its appeal.', 'In this imagined outing, a house host walks with a small group, pointing out the places worth pausing: a sheltered inlet, a wind-shaped pine, a flat rock warmed by the sun. Bring a water bottle, a hat and shoes with a little grip.'],
    sections: [{ title: 'A morning outside', text: 'Set out after breakfast, before the afternoon heat. The path includes loose stones and uneven ground; it is not a step-free route. Children are welcome with an adult.' }, { title: 'Make it your kind of walk', text: 'Ask about a shorter route or a slower pace. This is a fictional editorial offering; timing, suitability and any price are discussed in a locally saved demo inquiry.' }] },
  { slug: 'clay-and-quiet', title: 'An afternoon with clay.', subtitle: 'At the ceramics table', image: 'ceramics', detail: 'About 2½ hours · Small group · Fictional workshop',
    paragraphs: ['There is a particular kind of quiet that arrives when your hands have something to do. At a simple table, a lump of clay becomes a pinch bowl, a small cup, or something that is not quite either. The irregular edge is usually the best part.', 'This imagined afternoon takes its cues from the house’s own ceramics: useful shapes, earthy glazes, and pieces that feel good to hold. No experience is needed. There is time to begin again, and tea when you need it.'],
    sections: [{ title: 'Nothing to get right', text: 'An introductory hand-building session with tools, an apron and clay. Suitable for adults and children aged eight and above with a participating adult. The table is shaded and the pace is easy.' }, { title: 'From clay to keepsake', text: 'Firing and collection would be discussed during the inquiry. No workshop is reserved or physical object promised by this demo. Tell us the shape of your afternoon in a local inquiry.' }] },
  { slug: 'a-table-at-dusk', title: 'Stay for the last light.', subtitle: 'An evening tasting', image: 'evening', detail: 'About 90 minutes · At the house · Fictional tasting',
    paragraphs: ['The terrace changes character when the sun drops behind the house. Glasses catch the remaining light. The kitchen brings out small plates in no particular hurry: tomatoes still warm from the day, grilled vegetables, a spoonful of something bright and sharp.', 'Our imagined evening tasting is a conversation between the kitchen and the season. There are no speeches to sit through, only a few stories about what is on the table and enough time to enjoy it.'],
    sections: [{ title: 'A taste of the place', text: 'Five small plates with a choice of a botanical, alcohol-free pairing or a wine pairing for adults. The sample concept is seasonal and can change. Tell us about allergies before discussing a menu; suitability is not guaranteed.' }, { title: 'A place at the table', text: 'Designed for a small gathering on the shaded terrace or in the breakfast room. Save an inquiry to explore this fictional offering. It creates a local record, not a confirmed dining reservation.' }] },
];
export const JOURNAL: Story[] = [
  { slug: 'a-house-made-of-light', title: 'A house made of light.', subtitle: 'Architecture & atmosphere', image: 'courtyard', detail: '4 minute read',
    paragraphs: ['Before we imagined a single piece of furniture, we imagined the shadows. A deep window reveal at midday. The moving pattern of olive leaves on a courtyard wall. A rectangle of evening sun crossing the floor of a room. Light is the material that costs nothing and changes everything.', 'Aurel House was conceived from the outside in. Its two-storey form gathers around a courtyard, a sheltered middle where the coastal wind softens and the pace drops. Pale stone holds a little of the day’s warmth. The arches are there to make passages feel generous, not grand.', 'Inside, the palette stays close to what is outside: the chalk of limestone, the brown of olive bark, the deep green of water in shade. Walnut gives the hand somewhere warm to land. Linen moves when a window opens. Bronze is allowed to look like it has been touched.'],
    sections: [{ title: 'Enough, and no more', text: 'A small house asks for careful choices. A chair should be comfortable enough to finish a book in. A bedside light should fall on a page, not in someone else’s eyes. A shelf should hold a glass of water and a few things brought from home. These are quiet decisions, but they are the ones that turn a room into a place to stay.' }, { title: 'A changing room', text: 'The rooms are designed to look different at nine in the morning and six in the evening. We would rather let daylight do that work than fill every surface. This is a fictional house, but the design question behind it is a real one: how little does a room need, if everything in it has been considered?' }] },
  { slug: 'breakfast-takes-its-time', title: 'Breakfast takes its time.', subtitle: 'Notes from the table', image: 'dining', detail: '3 minute read',
    paragraphs: ['The first sound is a cup meeting its saucer. Then a chair being pulled across stone, the turn of a page, someone asking for another piece of bread. Breakfast at the imagined Aurel House is a collection of small sounds, none of them urgent.', 'We begin with things that need little explanation: bread with a crisp crust, yogurt in a handmade bowl, fruit cut when it is ready to be eaten. Honey catches the light. Olive oil is poured with an unsteady, generous hand. Coffee arrives when you sit down.', 'The tableware matters because it disappears into the experience. The bowl fits your palm. The cup keeps its warmth. No two glazed surfaces are quite alike, which seems a useful thing to remember at the beginning of a day.'],
    sections: [{ title: 'Leave a little room', text: 'A breakfast should leave space for the rest of the morning. There might be eggs with herbs, roasted tomatoes or a small piece of cake. There need not be everything. Our sample menu is a starting point for this fictional kitchen, with seasonal variation written into its character.' }, { title: 'The best seat', text: 'It could be under the pergola, where the stripes of shade move between courses. It could be inside by the open doors. The best seat is the one where you stop thinking about where you should be next.' }] },
  { slug: 'the-art-of-staying-put', title: 'The art of staying put.', subtitle: 'A slower kind of travel', image: 'pool', detail: '3 minute read',
    paragraphs: ['There is a familiar temptation when you arrive somewhere new: find the list, mark the places, make a plan. The days begin to resemble the itinerary before you have noticed the color of the water. We imagined Aurel House as a small invitation to try the opposite.', 'Staying put is not doing nothing. It is learning which chair gets the first sun, when the pool falls into shade, and how long the walk to the water takes without looking at your phone. It is returning to the same view and noticing that it is never exactly the same.', 'A twelve-room house can offer a different scale of travel. The spaces are small enough to become familiar. The garden is close enough to hear. A quiet corner is somewhere you can find again tomorrow.'],
    sections: [{ title: 'An unfilled afternoon', text: 'Leave one afternoon without a destination. Take a book that you do not have to finish. Swim once, then again. Let lunch run late. A good trip does not always need a highlight reel; sometimes it leaves you with a particular quality of light and a little more room in your thoughts.' }, { title: 'Take the rhythm home', text: 'The useful souvenir is often a habit. Breakfast sitting down. A short walk without a purpose. A table laid with care on an ordinary evening. Our house is fictional; the possibility of a slower day is not.' }] },
];
export const FAQS = [
  ['Is Aurel House a real hotel?', 'No. Aurel House is a fictional agency portfolio project. Bookings, payments, messages and inquiries are browser-only simulations. No actual room, meal or experience is reserved.'],
  ['When can I check in and out?', 'The fictional check-in time is from 15:00 and checkout is by 11:00, in Europe/Athens. The $40 late-checkout option simulates a confirmed extension to 14:00.'],
  ['What is the cancellation policy?', 'Cancel a confirmed stay any calendar day before arrival for a full simulated refund. On the arrival date or after check-in, save a local inquiry instead.'],
  ['Are children welcome?', 'Yes. In this simplified demo, children are ages 2–11. At least one adult is required. Sea Studios sleep up to three using a single daybed; Aurel Suites sleep up to four using a double sofa bed. No infant pricing is modeled.'],
  ['Is breakfast included?', 'Breakfast is optional: $18 per adult and $9 per child, for each night of the stay. Choose it during booking. No extras are selected automatically.'],
  ['Can I book more than one room?', 'Each reservation covers one physical room. For a group or several rooms, use the local contact form and choose Group stay. There is no multi-room checkout.'],
  ['Which rooms look out to sea?', 'Sea Studios have sea-facing windows. Aurel Suites have private sea-facing terraces. Courtyard Rooms face the planted courtyard; Terrace Rooms have planted terraces without a guaranteed sea view.'],
  ['Can you accommodate access or dietary needs?', 'The fictional specification includes uneven stone paths and does not establish step-free access. Ask through the local inquiry form about access or dietary needs; the demo does not guarantee suitability or allergy-safe food.'],
  ['Where are my reservations saved?', 'Only in this browser profile on this website’s origin. Same-origin tabs share data. A separate browser, device or private context has its own state. Clearing site data removes records.'],
  ['Will I receive an email or be charged?', 'No. Payment is simulated, and confirmation messages are previews saved locally. Use fictional guest information. There is no email delivery, payment integration or account sign-in.'],
];
