import { PageIntro, TextLink } from '@/components/editorial';
import { DISCLOSURE } from '@/lib/catalog';
export const metadata = { title: 'The details of your stay', description: 'Fictional stay, pricing, cancellation, privacy and storage policies for the Aurel House portfolio demo.' };
const policies = [
  ['The nature of this house', DISCLOSURE + ' Aurel House is a fictional working concept, with no real address, operator, verified trademark or registered domain claim.'],
  ['Dates and guests', 'One reservation books one physical room for 1–14 nights. Arrival is allowed from the hotel’s current date through the next 365 days, with departure by day 366. All calendar rules use Europe/Athens independently of your own timezone. At least one adult is required. Children are ages 2–11; infant pricing is outside the demo. Total guests must fit the room.'],
  ['Arrival and departure', 'Check-in is from 15:00 and checkout is by 11:00. The optional $40 late-checkout simulation extends checkout to 14:00. It does not occupy an extra night; the next guest may arrive from 15:00. A departure date is available for another arrival.'],
  ['The price you see', 'USD prices are stored in integer cents. Friday and Saturday nights add 15%; June, July and August nights add 20%. When both apply, factors multiply before the nightly amount is rounded once. All fictional taxes and fees are included. There are no deposits, promotions, currency conversions or unexplained charges.'],
  ['A few extras', 'Breakfast is optional at $18 per adult and $9 per child for each night. A simulated airport transfer costs $65 once per reservation. Late checkout costs $40 once and is a simulated confirmed option. Nothing is selected automatically. Dining and experiences use separate local inquiries.'],
  ['Changing your stay', 'A confirmed reservation arriving after today may change dates, room, guests or extras, subject to a single room being available for the whole replacement stay. You see the new total and simulated charge or refund difference before accepting. A failed change preserves your original reservation. Accepted prices are snapshots; later local rate edits never change them.'],
  ['Cancellation', 'A confirmed reservation can be cancelled until the calendar day before arrival for a full simulated refund. On the arrival date or after check-in, use the local inquiry form. Cancelling releases its nights immediately in this browser. No actual money is charged or refunded.'],
  ['Shared spaces and suitability', 'The fictional pool is open 08:00–20:00, breakfast 07:30–10:30, dinner 18:30–21:30, and the reading lounge all day. Children require adult supervision by the pool. Stone paths may be uneven; the specification does not establish step-free access. Ask locally about access, allergies or dietary requirements. The demo does not guarantee suitability. No smoking indoors; quiet hours are 22:00–08:00 in the fictional house.'],
  ['Your local data', 'Please use fictional names and example-domain email addresses. Drafts, guest details, inquiries and reservations stay in localStorage on this origin. Same-origin tabs in the same browser profile share data. Separate browsers, devices, origins and private contexts do not have shared reservations. Clearing site data removes your records. This user-editable browser store is not secure authentication or authorization.'],
  ['Storage, messages and payments', 'There are no analytics, outbound form submissions, real payment details or email delivery. Confirmation messages are local previews. If storage fails, the app offers an explicit temporary-session mode; its changes disappear on reload. Browser storage cannot guarantee atomic bookings across tabs and does not represent shared live hotel availability. Reset removes only this application’s namespaced records.'],
];
export default function Page() { return <div className="wrap"><PageIntro title="The details of your stay." text="Clear, simple policies for a fictional house. These rules describe the demonstration, not a real travel service." /><article className="policy-list">{policies.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}<TextLink href="/demo/">Explore how the demo works</TextLink></article></div>; }
