import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({channel:'chrome',headless:true});
const base=process.env.AUREL_PREVIEW_URL||'http://127.0.0.1:3001', KEY='aurel-house:demo:v1';
const time=new Date('2026-09-09T09:00:00Z');
const report={clock:time.toISOString(),base,browser:browser.version(),flows:[],routes:[],screenshots:[],accessibility:[],performance:[],errors:[]};
await fs.mkdir('docs/screenshots',{recursive:true}); await fs.mkdir('test-results',{recursive:true});
const local=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
async function newPage(ctx,width=1440,height=1000){const p=await ctx.newPage();await p.setViewportSize({width,height});await p.clock.setFixedTime(time);p.setDefaultTimeout(10000);p.on('pageerror',e=>report.errors.push(e.message));return p;}
async function run(name,fn){try{await fn();report.flows.push({name,passed:true});console.log(`PASS ${name}`);}catch(e){report.flows.push({name,passed:false});report.errors.push(`${name}: ${e.message} URL: ${p.url()}`);console.log(`FAIL ${name}: ${e.message}`);}}
const goto=async(p,route)=>{const r=await p.goto(base+route,{waitUntil:'networkidle'});return r;};
const button=(p,name)=>p.getByRole('button',{name,exact:true});
const field=(p,name)=>p.getByLabel(name,{exact:true});
const next=p=>button(p,'Continue').click();
async function capture(p,name){await p.evaluate(async()=>{await document.fonts.ready;const images=[...document.images];images.forEach(i=>i.loading='eager');await Promise.all(images.map(i=>i.decode().catch(()=>{})));scrollTo(0,0);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});for(const image of await p.locator('img').all()){if(await image.isVisible()){await image.scrollIntoViewIfNeeded();await image.evaluate(async el=>{await el.decode().catch(()=>{});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});}}await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:`docs/screenshots/${name}-viewport.png`});await p.screenshot({path:`docs/screenshots/${name}.png`,fullPage:true});report.screenshots.push(name);}
async function axe(p,name){const r=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();report.accessibility.push({page:name,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}
const ctx=await browser.newContext({reducedMotion:'reduce',acceptDownloads:true});const p=await newPage(ctx);let ref,snapshot;
if(process.argv.includes('--diagnose')){await p.setViewportSize({width:390,height:844});await goto(p,'/admin/');console.log(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect();return r.right>innerWidth+1&&!el.closest('.table-scroll')}).map(el=>({tag:el.tagName,cls:el.className,rect:el.getBoundingClientRect().toJSON(),position:getComputedStyle(el).position})).slice(0,25)})));await goto(p,'/dining/');const target=p.locator('.editorial-panorama');console.log(await target.locator('img').evaluate(el=>({complete:el.complete,src:el.currentSrc,rect:el.getBoundingClientRect().toJSON(),css:el.style.cssText,visibility:getComputedStyle(el).visibility,opacity:getComputedStyle(el).opacity})));await target.scrollIntoViewIfNeeded();await target.locator('img').evaluate(el=>el.decode());await target.screenshot({path:'docs/screenshots/dining-image-diagnostic.png'});await browser.close();process.exit(0);}
await run('date validation, useful sample dates, refresh and back/forward preserve draft',async()=>{
 await goto(p,'/book/');await next(p);await p.getByText('Choose a valid arrival date.').waitFor();await button(p,'Try sample dates').click();assert.ok((await local(p)).draft.arrival>'2026-09-09');
 await field(p,'Arrival').fill('2026-10-06');await field(p,'Departure').fill('2026-10-09');await p.reload({waitUntil:'networkidle'});assert.equal((await local(p)).draft.arrival,'2026-10-06');
 await p.getByRole('link',{name:'Back to the rooms'}).click();await p.locator('.room-index-row').first().getByRole('link',{name:'Step inside'}).click();await button(p,'Find your stay').click();await p.waitForURL(/\/book\//);await p.goBack({waitUntil:'networkidle'});await p.waitForURL(/rooms\/courtyard-room/);await p.goForward({waitUntil:'networkidle'});await p.waitForURL(/\/book\//);assert.equal((await local(p)).draft.departure,'2026-10-09');
});
await run('quote, decline without inventory effects, duplicate-click success and refresh',async()=>{
 await goto(p,'/book/');await next(p);await p.getByRole('radio',{name:'Select Courtyard Room'}).check();await next(p);await p.getByLabel(/A slow breakfast/).check();await p.getByLabel(/An easy arrival/).check();await next(p);await button(p,'Use sample guest').click();await next(p);assert.equal(await p.locator('.price-total strong').textContent(),'$743');
 await p.locator('.nightly-breakdown summary').click();await capture(p,'booking-desktop');await p.setViewportSize({width:390,height:844});await capture(p,'booking-mobile');assert.ok(await p.locator('.booking-summary').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('.consent').getBoundingClientRect().top),'Review total and stay must precede consent on mobile');await axe(p,'booking-review');await p.setViewportSize({width:1440,height:1000});
 await p.getByText('Demo payment scenario',{exact:true}).click();await field(p,'Simulated result').selectOption('decline');await p.getByLabel(/I understand this is a browser-only/).check();const before=await local(p);await button(p,'Confirm demo reservation').click();await p.getByText(/The demo payment was declined/).waitFor();assert.deepEqual((await local(p)).reservations,before.reservations);assert.deepEqual((await local(p)).messages,before.messages);
 await field(p,'Simulated result').selectOption('success');await p.getByLabel(/I understand this is a browser-only/).check();await button(p,'Confirm demo reservation').evaluate(b=>{b.click();b.click();});await p.waitForURL(/booking\/confirmation/);const s=await local(p),visitors=s.reservations.filter(r=>r.source==='visitor');assert.equal(visitors.length,1);assert.equal(s.messages.length,1);ref=visitors[0].ref;assert.equal(visitors[0].quote.total,74300);assert.equal(visitors[0].unitId,'C01');
 await p.reload({waitUntil:'networkidle'});await p.getByRole('heading',{name:'A little time, just for you.'}).waitFor();await capture(p,'confirmation-desktop');await p.setViewportSize({width:390,height:844});await capture(p,'confirmation-mobile');await axe(p,'confirmation');await p.setViewportSize({width:1440,height:1000});snapshot=await local(p);
});
await run('calendar, print and same reservation in guest list and front desk',async()=>{
 assert.ok(ref);const pending=p.waitForEvent('download');await button(p,'Download calendar').click();const download=await pending;await download.saveAs(`test-results/${ref}.ics`);const text=await fs.readFile(`test-results/${ref}.ics`,'utf8');assert.ok(text.includes('DTSTART;VALUE=DATE:20261006'));assert.ok(text.includes('DTEND;VALUE=DATE:20261009'));
 await p.emulateMedia({media:'print'});await p.pdf({path:'docs/screenshots/confirmation-print.pdf',preferCSSPageSize:true,printBackground:true});assert.equal(await p.locator('.site-header').isVisible(),false);await p.emulateMedia({media:'screen'});
 await goto(p,'/my-stay/');await p.getByText(ref,{exact:true}).waitFor();await goto(p,'/admin/');await button(p,'Reservations').click();await field(p,'Search guests, rooms or references').fill(ref);await button(p,`Open ${ref}`).click();await p.locator('.reservation-drawer').getByText(ref,{exact:true}).waitFor();await button(p,'Close reservation details').click();
});
await run('rate edits synchronize tabs and preserve accepted quote',async()=>{
 const other=await newPage(ctx);await goto(other,'/rooms/courtyard-room/');await button(p,'Rooms & rates').click();await field(p,'Base rate · USD/night').first().fill('205');await p.locator('.room-editor').first().getByRole('button',{name:'Save local room changes'}).click();await other.getByText('From $205',{exact:true}).first().waitFor();assert.equal((await local(other)).reservations.find(r=>r.ref===ref).quote.total,74300);await other.close();
});
await run('maintenance rejects reservation overlap and changes valid unit availability',async()=>{
 await button(p,'Maintenance').click();await field(p,'Physical room unit').selectOption('C01');await field(p,'Reason').fill('QA limewash care');await field(p,'First blocked night').fill('2026-10-06');await field(p,'Available again on').fill('2026-10-07');const before=(await local(p)).maintenance.length;await button(p,'Save maintenance block').click();await p.locator('.dashboard > .form-alert').filter({hasText:'This block conflicts with'}).waitFor();assert.equal((await local(p)).maintenance.length,before);await field(p,'Physical room unit').selectOption('C04');await button(p,'Save maintenance block').click();assert.equal((await local(p)).maintenance.length,before+1);await button(p,'Availability').click();await field(p,'Dashboard date').fill('2026-10-06');const row=p.locator('.availability-table tbody tr').filter({has:p.getByRole('rowheader',{name:/^C04/})});assert.ok((await row.textContent()).includes('Maintenance'));
});
await run('invalid amendment preserves original; valid change accepts simulated difference',async()=>{
 await goto(p,`/my-stay/details/?ref=${ref}`);await p.getByRole('link',{name:'Change your stay'}).click();await field(p,'Departure').fill('2026-10-05');await next(p);await p.getByText(/Departure must be after arrival/).waitFor();assert.equal((await local(p)).reservations.find(r=>r.ref===ref).departure,'2026-10-09');await field(p,'Arrival').fill('2026-10-07');await field(p,'Departure').fill('2026-10-10');await next(p);await p.getByRole('radio',{name:'Select Terrace Room'}).check();for(let i=0;i<3;i++)await next(p);await p.getByText('Simulated additional charge',{exact:true}).waitFor();assert.equal(await p.locator('.price-total strong').textContent(),'$960.50');await p.getByLabel(/I understand this is a browser-only/).check();await button(p,'Accept change and simulated difference').click();await p.waitForURL(/my-stay\/details/);const r=(await local(p)).reservations.find(r=>r.ref===ref);assert.equal(r.roomSlug,'terrace-room');assert.equal(r.arrival,'2026-10-07');assert.equal(r.adjustments[0].amount,21750);
});
await run('cancel once, full simulated refund and no repeated cancellation control',async()=>{
 await button(p,'Cancel demo stay').click();await button(p,'Confirm cancellation').click();await p.getByRole('heading',{name:'Until another time.'}).waitFor();const r=(await local(p)).reservations.find(r=>r.ref===ref);assert.equal(r.status,'cancelled');assert.equal(r.refunded,96050);await p.reload({waitUntil:'networkidle'});assert.equal((await local(p)).activity.filter(a=>a.id===`cancelled-${ref}`).length,1);assert.equal(await button(p,'Cancel demo stay').count(),0);
});
await run('inquiries validate, save locally and appear alongside local message previews',async()=>{
 await goto(p,'/contact/?subject=Dining%20inquiry');await button(p,'Save demo inquiry').click();await p.getByText(/Enter a fictional full name/).waitFor();await button(p,'Use sample guest').click();await button(p,'Save demo inquiry').click();await p.getByRole('heading',{name:'Saved in this demo.'}).waitFor();await goto(p,'/admin/');await button(p,'Inquiries & messages').click();await p.getByText('Dining inquiry',{exact:true}).waitFor();await p.locator('.message-preview').filter({hasText:`Your demo stay at Aurel House · ${ref}`}).locator('summary').click();await p.getByText(/This is a local message preview. No email has been sent./).waitFor();
});
await run('separate browser context has independent state and missing-booking explanation',async()=>{
 const isolated=await browser.newContext();const other=await newPage(isolated);await goto(other,`/booking/confirmation/?ref=${ref}`);await other.getByRole('heading',{name:/This stay isn’t/}).waitFor();assert.equal((await local(other)).reservations.filter(r=>r.source==='visitor').length,0);await isolated.close();
});
await run('scoped reset preserves unrelated data and synchronizes tabs',async()=>{
 const other=await newPage(ctx);await goto(other,'/my-stay/');await p.evaluate(()=>localStorage.setItem('unrelated:sentinel','preserve'));await goto(p,'/demo/');await button(p,'Reset sample house').click();await button(p,'Confirm reset').click();await other.getByRole('heading',{name:'A little time away, yet to come.'}).waitFor();assert.equal((await local(other)).reservations.filter(r=>r.source==='visitor').length,0);assert.equal(await p.evaluate(()=>localStorage.getItem('unrelated:sentinel')),'preserve');assert.equal((await local(p)).inquiries.length,0);assert.equal((await local(p)).draft.arrival,'');await other.close();
});
await run('corrupt storage preserved with recovery and explicit temporary fallback',async()=>{
 const c=await browser.newContext();const other=await newPage(c);await other.addInitScript(k=>localStorage.setItem(k,'{corrupt'),KEY);await goto(other,'/demo/');await button(other,'Download preserved recovery data').waitFor();assert.equal(await other.evaluate(k=>localStorage.getItem(k),KEY),'{corrupt');await other.locator('.storage-warning').getByRole('button',{name:'Use temporary-session mode'}).click();await button(other,'Try a sample stay').click();await button(other,'Continue').waitFor();assert.equal(await other.evaluate(k=>localStorage.getItem(k),KEY),'{corrupt');await c.close();
});
await run('disabled storage keeps browsing and temporary room selection usable',async()=>{
 const c=await browser.newContext();const other=await newPage(c);await other.addInitScript(()=>Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('Storage disabled','SecurityError');}}));await goto(other,'/demo/');await other.locator('.storage-warning').getByRole('button',{name:'Use temporary-session mode'}).click();await button(other,'Try a sample stay').click();await next(other);await other.getByRole('heading',{name:'Find your kind of room.'}).waitFor();await c.close();
});
await run('mobile keyboard, date sheet, navigation and lightbox focus restoration',async()=>{
 const c=await browser.newContext({reducedMotion:'reduce'});const other=await newPage(c,390,844);await goto(other,'/');await other.getByRole('button',{name:'Choose your dates'}).click();await other.locator('.availability-dialog').waitFor();await other.keyboard.press('Tab');assert.equal(await other.evaluate(()=>!!document.activeElement.closest('dialog')),true);await other.keyboard.press('Escape');assert.equal(await other.evaluate(()=>document.activeElement.classList.contains('search-mobile-summary')),true);await button(other,'Open navigation').click();await other.keyboard.press('Escape');assert.equal(await button(other,'Open navigation').evaluate(el=>el===document.activeElement),true);
 await goto(other,'/rooms/courtyard-room/');await other.locator('.gallery-item').first().click();await button(other,'Next image').click();await other.keyboard.press('ArrowRight');await other.keyboard.press('Escape');assert.equal(await other.locator('.gallery-item').first().evaluate(el=>el===document.activeElement),true);await button(other,'Find your stay').click();await button(other,'Try sample dates').click();await button(other,'Continue').focus();await other.keyboard.press('Enter');await other.getByRole('heading',{name:'Find your kind of room.'}).waitFor();await c.close();
});
const routes=['/','/rooms/','/rooms/courtyard-room/','/rooms/terrace-room/','/rooms/sea-studio/','/rooms/aurel-suite/','/the-house/','/dining/','/experiences/','/experiences/along-the-coast/','/experiences/clay-and-quiet/','/experiences/a-table-at-dusk/','/gallery/','/journal/','/journal/a-house-made-of-light/','/journal/breakfast-takes-its-time/','/journal/the-art-of-staying-put/','/contact/','/faq/','/policies/','/book/','/booking/confirmation/','/my-stay/','/my-stay/details/','/demo/','/admin/'];
await run('26 exported routes direct navigation and refresh; genuine 404',async()=>{
 for(const route of routes){const r=await goto(p,route);assert.equal(r.status(),200,route);await p.reload({waitUntil:'networkidle'});assert.equal(await p.locator('main h1').count(),1,route);assert.ok((await p.locator('meta[name="robots"]').getAttribute('content')).includes('noindex'));report.routes.push(route);}const r=await goto(p,'/a-real-missing-page/');assert.equal(r.status(),404);await p.getByRole('heading',{name:/This way leads/}).waitFor();
});
await run('batched screenshots, image integrity, 360/390/768/1024/1440 widths and axe checks',async()=>{
 const shots=[['home','/'],['room','/rooms/courtyard-room/'],['house','/the-house/'],['dining','/dining/'],['experiences','/experiences/'],['article','/journal/a-house-made-of-light/'],['gallery','/gallery/'],['contact','/contact/'],['faq','/faq/'],['policies','/policies/'],['demo','/demo/'],['admin','/admin/']];
 for(const [name,route]of shots){for(const [device,width,height]of [['desktop',1440,1000],['mobile',390,844]]){await p.setViewportSize({width,height});await goto(p,route);await capture(p,`${name}-${device}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name}-${device} overflow`);assert.deepEqual(await p.locator('img').evaluateAll(images=>images.filter(i=>i.naturalWidth===0).map(i=>i.currentSrc)),[],`${name}-${device} images`);if(device==='mobile'&&['home','room','contact','admin','demo'].includes(name))await axe(p,name);}}
 for(const width of [360,768,1024])for(const route of ['/','/rooms/aurel-suite/','/book/','/admin/']){await p.setViewportSize({width,height:900});await goto(p,route);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${route} ${width}px overflow`);}
 await p.setViewportSize({width:390,height:844});await goto(p,'/book/');await button(p,'Try sample dates').click();await next(p);await axe(p,'booking-rooms');
});
await run('cold mobile performance under 4x CPU, 150ms RTT, 1.6Mbps down',async()=>{
 for(const route of ['/','/rooms/courtyard-room/','/book/']){const c=await browser.newContext({isMobile:true,hasTouch:true,deviceScaleFactor:1});const other=await newPage(c,390,844);const cdp=await c.newCDPSession(other);let bytes=0;cdp.on('Network.loadingFinished',event=>bytes+=event.encodedDataLength);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:1.6*1024*1024/8,uploadThroughput:750*1024/8});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await other.addInitScript(()=>{window.__aurelPerf={lcp:0,cls:0,fcp:null};new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.name==='first-contentful-paint')window.__aurelPerf.fcp=e.startTime;}).observe({type:'paint',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())window.__aurelPerf.lcp=e.startTime;}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)window.__aurelPerf.cls+=e.value;}).observe({type:'layout-shift',buffered:true});});await other.goto(base+route,{waitUntil:'networkidle',timeout:60000});await other.evaluate(()=>document.fonts.ready);const metrics=await other.evaluate(()=>({fcp:window.__aurelPerf.fcp,lcp:window.__aurelPerf.lcp,cls:window.__aurelPerf.cls,transferBytes:performance.getEntriesByType('resource').reduce((sum,r)=>sum+r.transferSize,0)}));report.performance.push({route,...metrics,transferBytes:bytes});await c.close();}
});
if(snapshot)await fs.writeFile('test-results/visitor-snapshot.json',JSON.stringify(snapshot,null,2));
await fs.writeFile('docs/browser-results.json',JSON.stringify(report,null,2));await ctx.close();await browser.close();console.log(JSON.stringify({passed:report.flows.filter(f=>f.passed).length,total:report.flows.length,routes:report.routes.length,screenshots:report.screenshots.length,accessibilityViolations:report.accessibility.reduce((sum,p)=>sum+p.violations.length,0),performance:report.performance,errors:report.errors},null,2));if(report.errors.length)process.exitCode=1;
